###POST input captain to make e do
POST http://localhost:8080/api/dokOperations
Content-Type: application/json

{
  "poNumber": "PO1235",
  "vesselNumber": "test_vessel_number"
}

###GET all inspection operations by inspection officier
GET localhost:8080/api/ioOperations


###PUT start inspection of a ship with inspection number
PUT localhost:8080/api/ioOperations/IO-test_vessel_number

###GET all bunker operations by bunker officier
GET localhost:8080/api/boOperations

###PUT start bunkering of a ship with veseel number
PUT localhost:8080/api/boOperations/test_vessel_number

###GET dok operation for captain with vessel number
GET localhost:8080/api/dokOperations/test_vessel_number
